# Generated by Django 4.0.4 on 2022-05-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100)),
                ('ProjectBegin', models.DateField()),
                ('ProjectEnd', models.DateField()),
                ('ProjectValue', models.FloatField()),
                ('ProjectRisk', models.IntegerField()),
                ('ProjectPeople', models.CharField(max_length=1000)),
            ],
        ),
    ]
